### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by Fruit-Punch-Samurai** [BarrenWolfsbane/BAINSocial#1]
Hi, I'm the Reddit guy, I have some questions and remarks about the project:
1- Would you be willing to convert your project/part of it to Kotlin? that would make things much easier for future development.
2- minSdkVersion was set to 16 (old Android 4.1), updating it to 21 or 23 would reduce the amount of backwards  compatibility code that has to be written.
3- Could you add a README file explainging(briefly) what is the current state of the project and its roadmap*(I believe that's how it is called)?
4- I will be performing some formatting and refactoring on your codebase, mainly the Activities and view related classes.
5- This is my first time working on collaborative project...
6- Who's the girl???

**Comment by BarrenWolfsbane** [comment]
Hi!
1)Yes, however at the moment I have no experience with kotlin. if Java can
easily translate to kotlin it can be done at any stage of the project
including later ok after I have that knowledge
2) The min SDK was setup to reach the largest possible audience, if you
feel we can safely update to 21 or 23 but still hold a large share of users
then we can move on that. I simply balanced reach and function.
3) Yes, Ill get to work on that tonight. Mostly been blogging on Minds or
dropping updates on the discord. https://discord.gg/FfUQTaHJ
4) sounds good to me. I am fairly new to this so learning from you would be
a good experience
5) same here
6) That is me. The image on the login screen is just a placeholder. I do
have an artist who was given a concept to work with. Basically I am working
in my branding hence the project name

Finally we need to create a credits page. Something where you and any
others who contributed to this projects success can opt to gain credit for
what you contributed.
