### ISSUE TITLE
Collab

### ISSUE THREAD

**Issue by BarrenWolfsbane** [BarrenWolfsbane/BAINSocial#5]
Can I ask any who are making changes to this project to join us in discord or some other means to be able to chat?
To start I am inexperienced with GIT and mergers, Also I can provide better insight to errors if I can communicate direct with you

**Comment by BarrenWolfsbane** [comment]
One error on current main branch is the crash after login. This is a result of the BAIN Server not loading, this is likely due to manifest entry not being merged correctly as this works in the "testing" branch..

**Comment by Fruit-Punch-Samurai** [comment]
You can try this https://docs.github.com/en/discussions/quickstart

**Comment by BarrenWolfsbane** [comment]
it isn't much different from using the issue board to communicate TBH.
It also doesn't provide any screen share or speech.  which is unfortunate.
lastly in the discord I provided people are free to stream, which is a good opportunity to see where other devs are going
with their code.

Example, recently the issue you are having with that crash, I had fixed. I had pushed it to master and it is now in the "Testing" Branch. 

The way I had this setup was I had one activity be the starting point, it would check for system service to ensure it was running and if not boot it. This starts up an Instance of BAIN Server which is a major component in the backend. It keep the app running while closed and stores the global variables for the project. 

This reduces the need to pass variables in many cases as calls to BAINServer.getInstance() could be made followed by access to the public methods that are storing the variable we need. 
The crash was happening at a call to 
        BAINServer.getInstance().getUser().setHashedPass(hashedPass);
Because the Server never started and the user was never stored as a result. so the HashedPass could not be stored in that user.

**Comment by Fruit-Punch-Samurai** [comment]
Then I suggest you add a discord link to the README file for everyone to see, I don't speak English or use Discord a lot, but I agree that it would make communication easier.

**Comment by BarrenWolfsbane** [comment]
On another note, the Server Selection fragment was just a placeholder. As was much of the code for communications.
I was using the examples for socks communications as a template to try and better understand the means to setup a server/client system. It will not be the screen we will drop into once we have determined the key was created.
I need to design a UI layout tonight though we are trying to come up with an idea on how it should appear.

Discord link is already attached to the Project here: https://github.com/BarrenWolfsbane/BAINSocial On the right side of screen.
The link itself is this. https://discord.gg/sbpw6Hm8RV

**Comment by BarrenWolfsbane** [comment]
An issue I am having right now is much of the project shows up red in the editor. It still compiles ok and runs but the editor shows errors

**Comment by BarrenWolfsbane** [comment]
I will pit a discord Link into the README file
